In [1]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None) 
pd.set_option("display.max_colwidth", None)

In [28]:
boxscore_df = pd.read_csv("../tests/test_data/test_cleaned_boxscores.csv")
games_df = pd.read_csv("../tests/test_data/test_cleaned_games.csv")

In [35]:
games_subset = games_df[["game_id", "season_start_year", "home_team", "points_home", "away_team", "points_away"]]
merged_df = boxscore_df.merge(games_subset, how="inner", on="game_id")

merged_df.head()

,game_id,team_name,player_name,minutes_played,field_goals,field_goals_attempted,three_pointers,three_pointers_attempted,free_throws,free_throws_attempted,total_rebounds,assists,points,is_starter,field_goals_percentage_%,three_point_percentage_%,season_start_year,home_team,points_home,away_team,points_away
0,23859,Cleveland Cavaliers,Mo Williams,37:09,7,15,3,7,2,3,4,7,19,1,46.67,42.86,2015,Chicago Bulls,97,Cleveland Cavaliers,95
1,23859,Cleveland Cavaliers,LeBron James,36:04,12,22,1,5,0,3,10,5,25,1,54.55,20.00,2015,Chicago Bulls,97,Cleveland Cavaliers,95
2,23859,Cleveland Cavaliers,Kevin Love,34:49,6,17,3,7,3,3,8,4,18,1,35.29,42.86,2015,Chicago Bulls,97,Cleveland Cavaliers,95
3,23859,Cleveland Cavaliers,J.R. Smith,30:27,3,10,0,2,2,4,5,3,8,1,30.00,0.00,2015,Chicago Bulls,97,Cleveland Cavaliers,95
4,23859,Cleveland Cavaliers,Timofey Mozgov,20:54,2,6,0,0,1,2,5,2,5,1,33.33,0.00,2015,Chicago Bulls,97,Cleveland Cavaliers,95

In [33]:
# Who scored the most 3 pointers per year (regular season and pre season and friendlies)?
player_year_totals = merged_df.groupby(['season_start_year', 'player_name'])['three_pointers'].sum().reset_index()

top_scorers_all_years = player_year_totals.loc[player_year_totals.groupby('season_start_year')['three_pointers'].idxmax()]

top_scorers_all_years.head(5)

      season_start_year    player_name  three_pointers
423                2015  Stephen Curry             482
903                2016  Stephen Curry             396
1187               2017   James Harden             317
1972               2018  Stephen Curry             446
2274               2019   James Harden             338